apiVersion: v1
kind: Service
metadata:
    name: php-app-service
    labels:
        app: php-app
spec:
    type: NodePort
    ports:
        - port: 80
          targetPort: 80
          nodePort: 30080
          protocol: TCP
          name: http
    selector:
        app: php-app
---
apiVersion: v1
kind: Service
metadata:
    name: php-app-service-lb
    labels:
        app: php-app
spec:
    type: LoadBalancer
    ports:
        - port: 80
          targetPort: 80
          protocol: TCP
          name: http
    selector:
        app: php-app
